version: '3.8'

services:
   ner:
       image: ner:prod
       command: gunicorn --bind 0.0.0.0:5000 server:app
       expose:
           - 5000
   nginx:
       build: ./nginx
       ports:
           - 1337:80
       depends_on:
           - ner
