version: '3.8'

services:
   ner:
       build: ./src_python
       command: gunicorn --bind 0.0.0.0:5000 server:app
       expose:
           - 5000
   nginx:
       build: ./src_python/nginx
       ports:
           - 80:80
       depends_on:
           - ner
   certbot:
       image: certbot/certbot
