version: '3.8'

services:
   ner:
       build: ./src_python
       command: gunicorn --bind 0.0.0.0:5000 wsgi:app --preload -k gevent --worker-connections 5
       expose:
           - 5000
   frontend:
       build: 
           context: .
           dockerfile: Dockerfile
       ports:
           - 80:80
       stdin_open: true
       depends_on:
           - ner
